# Generated by Django 4.2.1 on 2023-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_user_activation_number_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_activation_number',
            field=models.CharField(max_length=100),
        ),
    ]
