# Generated by Django 4.2.1 on 2023-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_user_activation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_number',
            field=models.TextField(default='2f5f0746-0eb6-46a8-a1fb-33efbef1d119'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_activation_number',
            field=models.TextField(),
        ),
    ]
