# Generated by Django 4.2.1 on 2023-05-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_imageprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, serialize=False, to='user.imageprofile'),
            preserve_default=False,
        ),
    ]
