# Generated by Django 4.2.1 on 2023-05-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_id_user_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.imageprofile'),
        ),
    ]
