# Generated by Django 4.2.1 on 2023-05-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_profile',
            new_name='avatar',
        ),
    ]
