# Generated by Django 4.2.1 on 2023-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_image_profile_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='user_avatar',
        ),
    ]
