# Generated by Django 4.2.1 on 2023-06-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
