FROM --platform=$BUILDPLATFORM python:3.9-alpine AS builder
WORKDIR /bot
COPY requirements.txt /bot
RUN pip3 install -r requirements.txt --no-cache-dir
COPY ./bot /bot
ENTRYPOINT ["python3"] 
CMD ["main.py"]