# Generated by Django 4.2.1 on 2023-06-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamescreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescreenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot', to='games.games'),
        ),
    ]
