# Generated by Django 4.2.1 on 2023-06-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gamescreenshot_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='genere',
            field=models.ManyToManyField(null=True, to='games.gamegenere'),
        ),
    ]
