# Generated by Django 4.2.1 on 2023-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamegenere_games_genere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='genere',
            field=models.ManyToManyField(to='games.gamegenere'),
        ),
    ]
