# Generated by Django 4.2.1 on 2023-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_games_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescreenshot',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
