# Generated by Django 4.2.1 on 2023-06-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0003_alter_handbookscreenshot_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handbook',
            name='type',
        ),
        migrations.AddField(
            model_name='handbook',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='handbook.handbooktype'),
        ),
    ]
