# Generated by Django 4.2.1 on 2023-06-24 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_games_genere'),
        ('handbook', '0004_remove_handbook_type_handbook_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handbook', to='games.games'),
        ),
    ]
