# Generated by Django 4.2.1 on 2023-06-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_games_genere'),
        ('handbook', '0005_handbook_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handbook', to='games.games'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='handbook.handbooktype'),
        ),
    ]
