# Generated by Django 4.2.1 on 2023-06-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0006_alter_handbook_game_alter_handbook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='body',
            field=models.TextField(max_length=4000),
        ),
    ]
