# Generated by Django 4.2.1 on 2023-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0007_alter_handbook_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
