# Generated by Django 4.2.1 on 2023-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0008_handbook_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbookscreenshot',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
